name: CI/CD

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_URI: sqlite:///mlflow.db
      USE_REGISTRY: "false"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Installer les dependances
        run: pip install -r requirements.txt

      - name: Entrainer le modele
        run: python train_model.py

      - name: Executer les tests
        run: pytest tests/ -v -s

      - name: Faire remonter le modele
        uses: actions/upload-artifact@v4
        with:
          name: model
          path: model/